= Vert.x Consul 客户端

https://www.consul.io[Consul] 是一个在你的应用架构中提供服务发现和配置管理的工具。
Vert.x 的 Consul 客户端允许应用与 Consul 系统通过阻塞或非阻塞的 HTTP 接口交互。

== 使用 Vert.x Consul 客户端

为了使用该项目， 将以下依赖添加到你的构建描述文件的 _依赖配置_ 中：

* Maven (在你的 `pom.xml` 中):

[source,xml,subs="+attributes"]
----
<dependency>
 <groupId>io.vertx</groupId>
 <artifactId>vertx-consul-client</artifactId>
 <version>4.0.3</version>
</dependency>
----

* Gradle (在你的 `build.gradle` 文件中):

[source,groovy,subs="+attributes"]
----
compile 'io.vertx:vertx-consul-client:4.0.3'
----

== 创建客户端

只需使用工厂方法即可创建：

[source,java]
----
ConsulClient client = ConsulClient.create(vertx);
----

Consul 客户端也可以配置选项

[source,java]
----
ConsulClientOptions options = new ConsulClientOptions()
  .setHost("consul.example.com");

ConsulClient client = ConsulClient.create(vertx, options);
----

Consul 客户端支持以下配置：

`host`:: Consul 的主机地址。 默认是 `localhost`
`port`:: Consul 的 HTTP 接口地址。 默认是 `8500`
`timeout`:: 设置超时时间 (单位为毫秒) 如果在超时时间内请求没有返回任何数据，那么
处理器会收到一个失败的结果，请求也会被关闭
`aclToken`:: ACL 签名。 如果设置了该参数， 客户端在请求 Consul 时会在
查询参数中携带 "?token" 参数。 如果没有提供，那么签名为空，会使用对应的 '匿名'
ACL 策略
`dc`:: 数据中心名称。 如果设置了该参数， 客户端在请求 Consul 时会在
查询参数中携带 "?dc" 参数。 如果没有提供，那么会默认查询当前的 Consul agent 的数据中心

ConsulClient 的选项类继承了 `vertx-web-client` 模块的 WebClientOptions 类，
因此还可以提供很多设置。 请参阅相关文档。

== 使用接口

客户端接口参见 `link:../../apidocs/io/vertx/ext/consul/ConsulClient.html[ConsulClient]`。 接口的格式与 Consul 的
HTTP 接口非常相像，Consul 的 HTTP 接口参见 https://www.consul.io/docs/agent/http.html[Consul API 文档]

=== 阻塞查询

Consul 的某些接口支持名为 "阻塞查询" 的特性。 阻塞查询基于长轮询以查询结果的潜在
变化。 每个支持阻塞查询的接口都提供了一个唯一标识 (index)，以代表
所请求资源的当前状态。 以下参数配置用于阻塞查询：

`index`:: 该值用于表示 Consul 客户端期望看到的所请求资源的 index 的变化
`wait`:: 该值用于表示阻塞查询的最大时间。 该值最大为 10 分钟。

[source,java]
----
BlockingQueryOptions opts = new BlockingQueryOptions()
  .setIndex(lastIndex)
  .setWait("1m");
----

要注意的是，阻塞查询不能 *严格保证* 所返回的数据确实是发生了变化的。
很有可能的情况是，阻塞查询的返回只是因为超时时间到了或发生了并没有改变数据内容的写入。

== 键值对存储

键值对接口用于访问 Consul 内部的简单键值对存储，这对保存服务的配置或其他元数据很有用。
以下是可以使用的接口

* 管理单个键值对的更新，删除和获取，以及根据键的前缀匹配的同样操作
* 管理通过单个原子性的事务操作来获取和更新键值对的操作

=== 从存储中获取键值对

Consul 客户端可以返回一个键的值

[source,java]
----
consulClient.getValue("key", res -> {
  if (res.succeeded()) {
    System.out.println("retrieved value: " + res.result().getValue());
    System.out.println("modify index: " + res.result().getModifyIndex());
  } else {
    res.cause().printStackTrace();
  }
});
----

...或者返回所有匹配某一给定前缀的键的值

[source,java]
----
consulClient.getValues("prefix", res -> {
  if (res.succeeded()) {
    System.out.println("modify index: " + res.result().getIndex());
    for (KeyValue kv : res.result().getList()) {
      System.out.println("retrieved value: " + kv.getValue());
    }
  } else {
    res.cause().printStackTrace();
  }
});
----

返回的键值对数据包括以下字段 (参见 https://www.consul.io/docs/agent/http/kv.html#single[文档]):

`createIndex`:: 内部的创建索引，表示该键值对何时被创建的
`modifyIndex`:: 更新索引，该键值对最后一次被修改时的索引
`lockIndex`:: 该键被成功获取锁的次数
`key`:: 键
`flags`:: 该键值对的标志位。 客户端可以选择使用标识位
来表示应用业务中的一些信息
`value`:: 值
`session`:: 拥有锁的会话

更新索引可以用于阻塞查询：

[source,java]
----
BlockingQueryOptions opts = new BlockingQueryOptions()
  .setIndex(modifyIndex)
  .setWait("1m");

consulClient.getValueWithOptions("key", opts, res -> {
  if (res.succeeded()) {
    System.out.println("retrieved value: " + res.result().getValue());
    System.out.println("new modify index: " + res.result().getModifyIndex());
  } else {
    res.cause().printStackTrace();
  }
});
----

=== 保存键值对

[source,java]
----
consulClient.putValue("key", "value", res -> {
  if (res.succeeded()) {
    String opResult = res.result() ? "success" : "fail";
    System.out.println("result of the operation: " + opResult);
  } else {
    res.cause().printStackTrace();
  }
});
----

保存请求也可以接受参数

[source,java]
----
KeyValueOptions opts = new KeyValueOptions()
  .setFlags(42)
  .setCasIndex(modifyIndex)
  .setAcquireSession("acquireSessionID")
  .setReleaseSession("releaseSessionID");

consulClient.putValueWithOptions("key", "value", opts, res -> {
  if (res.succeeded()) {
    String opResult = res.result() ? "success" : "fail";
    System.out.println("result of the operation: " + opResult);
  } else {
    res.cause().printStackTrace();
  }
});
----

以下是 `PUT` 请求可以接收的参数

`flags`:: 可以指定一个无符号数，范围是 `0` 到 `2^64^-1` 
客户端可以选择使用标识位来表示应用业务中的一些信息
`casIndex`:: 该标志位用于将 PUT 操作转为一次检查设置（Check-And-Set）操作。 如果你需要构建一个
拥有非常复杂同步原语的操作的话这回非常有用。 如果该索引值为 `0`， Consul 只会在键不存在的情况下
设置该键值对。 如果该索引不为 0， 该键值对只会在该索引与更新索引相匹配的时候被设置。
`acquireSession`:: 该标志位用于将 PUT 操作转为一次需要获取锁的操作。 这个参数可以让
Consul 在顶层发生领导选举。 如果锁未被获取并且会话有效，
那么该操作会增加锁索引（LockIndex） 并设置该键值对所属的会话以更新该键的值。
获取锁时键不一定存在。 如果锁已经被设置的会话持有， 那么锁索引
不会增加，但是键的内容还是会更新。 这是因为该会话当前已经拥有锁，可以直接更新键的内容，
而不用再释放锁并重新获取
`releaseSession`:: 该标志位用于将 PUT 操作转换为一次释放锁的操作。 跟 `acquireSession` 一起搭配
使用的话会很有用，这样可以让客户端生成一个锁。 该操作不会修改锁索引，但会释放
与该键相关联的会话。 前提是该键的锁正在被该会话持有。

=== 事务

当连接到 Consul 的 0.7 或更高的版本时， 客户端可以使用单次原子性的事务操作
来管理对多个键的更新和查询。 事务操作目前只支持键值对， 其他类型的
事务操作可能会在以后的版本中支持。
(参见 https://www.consul.io/docs/agent/http/kv.html#txn[文档]).

[source,java]
----
TxnRequest request = new TxnRequest()
  .addOperation(new TxnKVOperation().setKey("key1").setValue("value1").setType(TxnKVVerb.SET))
  .addOperation(new TxnKVOperation().setKey("key2").setValue("value2").setType(TxnKVVerb.SET));

consulClient.transaction(request, res -> {
  if (res.succeeded()) {
    System.out.println("succeeded results: " + res.result().getResults().size());
    System.out.println("errors: " + res.result().getErrors().size());
  } else {
    res.cause().printStackTrace();
  }
});
----

=== 删除键值对

最后， Consul 允许你从存储中删除键值对

[source,java]
----
consulClient.deleteValue("key", res -> {
  if (res.succeeded()) {
    System.out.println("complete");
  } else {
    res.cause().printStackTrace();
  }
});
----

...或者删除所有符合该前缀的键值对

[source,java]
----
consulClient.deleteValues("prefix", res -> {
  if (res.succeeded()) {
    System.out.println("complete");
  } else {
    res.cause().printStackTrace();
  }
});
----

== Services

One of the main goals of service discovery is to provide a catalog of available services.
To that end, the agent provides a simple service definition format to declare the availability of a service
and to potentially associate it with a health check.

=== Service registering

A service definition must include a `name` and may optionally provide an `id`, `tags`, `address`, `port`, and `checks`.

[source,java]
----
ServiceOptions opts = new ServiceOptions()
  .setName("serviceName")
  .setId("serviceId")
  .setTags(Arrays.asList("tag1", "tag2"))
  .setCheckOptions(new CheckOptions().setTtl("10s"))
  .setAddress("10.0.0.1")
  .setPort(8048);
----

`name`:: the name of service
`id`:: the `id` is set to the `name` if not provided. It is required that all services have a unique ID per node,
so if names might conflict then unique IDs should be provided.
`tags`:: list of values that are opaque to Consul but can be used to distinguish between primary or secondary nodes,
different versions, or any other service level labels.
`address`:: used to specify a service-specific IP address. By default, the IP address of the agent is used,
and this does not need to be provided.
`port`:: used as well to make a service-oriented architecture simpler to configure; this way,
the address and port of a service can be discovered.
`checks`:: associated health checks

These options used to register service in catalog:

[source,java]
----
consulClient.registerService(opts, res -> {
  if (res.succeeded()) {
    System.out.println("Service successfully registered");
  } else {
    res.cause().printStackTrace();
  }

});
----

=== Service discovery

Consul client allows to obtain actual list of the nodes providing a service

[source,java]
----
consulClient.catalogServiceNodes("serviceName", res -> {
  if (res.succeeded()) {
    System.out.println("found " + res.result().getList().size() + " services");
    System.out.println("consul state index: " + res.result().getIndex());
    for (Service service : res.result().getList()) {
      System.out.println("Service node: " + service.getNode());
      System.out.println("Service address: " + service.getAddress());
      System.out.println("Service port: " + service.getPort());
    }
  } else {
    res.cause().printStackTrace();
  }
});
----

It is possible to obtain this list with the statuses of the associated health checks.
The result can be filtered by check status.

[source,java]
----
consulClient.healthServiceNodes("serviceName", passingOnly, res -> {
  if (res.succeeded()) {
    System.out.println("found " + res.result().getList().size() + " services");
    System.out.println("consul state index: " + res.result().getIndex());
    for (ServiceEntry entry : res.result().getList()) {
      System.out.println("Service node: " + entry.getNode());
      System.out.println("Service address: " + entry.getService().getAddress());
      System.out.println("Service port: " + entry.getService().getPort());
    }
  } else {
    res.cause().printStackTrace();
  }
});
----

There are additional parameters for services queries

[source,java]
----
ServiceQueryOptions queryOpts = new ServiceQueryOptions()
  .setTag("tag1")
  .setNear("_agent")
  .setBlockingOptions(new BlockingQueryOptions().setIndex(lastIndex));
----

`tag`:: by default, all nodes matching the service are returned.
The list can be filtered by tag using the `tag` query parameter
`near`:: adding the optional `near` parameter with a node name will sort the node list in ascending order
based on the estimated round trip time from that node. Passing `near`=`_agent` will use the agent's node for the sort.
`blockingOptions`:: the blocking qyery options

Then the request should look like

[source,java]
----
consulClient.healthServiceNodesWithOptions("serviceName", passingOnly, queryOpts, res -> {
  if (res.succeeded()) {
    System.out.println("found " + res.result().getList().size() + " services");
  } else {
    res.cause().printStackTrace();
  }

});
----

=== Deregister service

Service can be deregistered by its ID:

[source,java]
----
consulClient.deregisterService("serviceId", res -> {
  if (res.succeeded()) {
    System.out.println("Service successfully deregistered");
  } else {
    res.cause().printStackTrace();
  }
});
----

== Health Checks

One of the primary roles of the agent is management of system-level and application-level health checks.
A health check is considered to be application-level if it is associated with a service.
If not associated with a service, the check monitors the health of the entire node.

[source,java]
----
CheckOptions opts = new CheckOptions()
  .setTcp("localhost:4848")
  .setInterval("1s");
----

The list of check options that supported by Consul client is:

`id`:: the check ID
`name`:: check name
`script`:: local path to checking script. Also you should set checking interval
`http`:: HTTP address to check. Also you should set checking interval
`ttl`:: Time to Live of check
`tcp`:: TCP address to check. Also you should set checking interval
`interval`:: checking interval in Go's time format which is sequence of decimal numbers,
each with optional fraction and a unit suffix, such as "300ms", "-1.5h" or "2h45m".
Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h"
`notes`:: the check notes
`serviceId`:: the service ID to associate the registered check with an existing service provided by the agent.
`deregisterAfter`:: deregister timeout. This is optional field, which is a timeout in the same time format as Interval and TTL.
If a check is associated with a service and has the critical state for more than this configured value,
then its associated service (and all of its associated checks) will automatically be deregistered.
The minimum timeout is 1 minute, and the process that reaps critical services runs every 30 seconds,
so it may take slightly longer than the configured timeout to trigger the deregistration.
This should generally be configured with a timeout that's much, much longer than any expected recoverable outage
for the given service.
`status`:: the check status to specify the initial state of the health check

The `Name` field is mandatory, as is one of `Script`, `HTTP`, `TCP` or `TTL`. `Script`, `TCP` and `HTTP`
also require that `Interval` be set. If an `ID` is not provided, it is set to `Name`.
You cannot have duplicate ID entries per agent, so it may be necessary to provide an ID.

[source,java]
----
consulClient.registerCheck(opts, res -> {
  if (res.succeeded()) {
    System.out.println("check successfully registered");
  } else {
    res.cause().printStackTrace();
  }
});
----

== Events

The Consul provides a mechanism to fire a custom user event to an entire datacenter.
These events are opaque to Consul, but they can be used to build scripting infrastructure to do automated deploys,
restart services, or perform any other orchestration action.

To send user event only its name is required

[source,java]
----
consulClient.fireEvent("eventName", res -> {
  if (res.succeeded()) {
    System.out.println("Event sent");
    System.out.println("id: " + res.result().getId());
  } else {
    res.cause().printStackTrace();
  }
});
----

Also additional options can be specified.

`node`:: regular expression to filter recipients by node name
`service`:: regular expression to filter recipients by service
`tag`:: regular expression to filter recipients by tag
`payload`:: an optional body of the event.
The body contents are opaque to Consul and become the "payload" of the event

[source,java]
----
EventOptions opts = new EventOptions()
  .setTag("tag")
  .setPayload("message");

consulClient.fireEventWithOptions("eventName", opts, res -> {
  if (res.succeeded()) {
    System.out.println("Event sent");
    System.out.println("id: " + res.result().getId());
  } else {
    res.cause().printStackTrace();
  }
});
----

The Consul Client supports queries for obtain the most recent events known by the agent. Events are broadcast using
the gossip protocol, so they have no global ordering nor do they make a promise of delivery. Agents only buffer
the most recent entries. The current buffer size is 256, but this value could change in the future.

[source,java]
----
consulClient.listEvents(res -> {
  if (res.succeeded()) {
    System.out.println("Consul index: " + res.result().getIndex());
    for(Event event: res.result().getList()) {
      System.out.println("Event id: " + event.getId());
      System.out.println("Event name: " + event.getName());
      System.out.println("Event payload: " + event.getPayload());
    }
  } else {
    res.cause().printStackTrace();
  }
});
----

The Consul Index can be used to prepare blocking requests:

[source,java]
----
EventListOptions opts = new EventListOptions()
  .setName("eventName")
  .setBlockingOptions(new BlockingQueryOptions().setIndex(lastIndex));

consulClient.listEventsWithOptions(opts, res -> {
  if (res.succeeded()) {
    System.out.println("Consul index: " + res.result().getIndex());
    for(Event event: res.result().getList()) {
      System.out.println("Event id: " + event.getId());
    }
  } else {
    res.cause().printStackTrace();
  }
});
----

== Sessions

Consul provides a session mechanism which can be used to build distributed locks.
Sessions act as a binding layer between nodes, health checks, and key/value data.
When a session is constructed, a node name, a list of health checks, a behavior, a TTL, and a lock-delay
may be provided.

[source,java]
----
SessionOptions opts = new SessionOptions()
  .setNode("nodeId")
  .setBehavior(SessionBehavior.RELEASE);
----

`lockDelay`:: can be specified as a duration string using an 's' suffix for seconds. The default is '15s'.
`name`:: can be used to provide a human-readable name for the Session.
`node`:: must refer to a node that is already registered, if specified. By default, the agent's own node name is used.
`checks`:: is used to provide a list of associated health checks. It is highly recommended that,
if you override this list, you include the default `serfHealth`.
`behavior`:: can be set to either `release` or `delete`. This controls the behavior when a session is invalidated.
By default, this is `release`, causing any locks that are held to be released. Changing this to `delete` causes
any locks that are held to be deleted. `delete` is useful for creating ephemeral key/value entries.
`ttl`:: is a duration string, and like `LockDelay` it can use s as a suffix for seconds. If specified,
it must be between 10s and 86400s currently. When provided, the session is invalidated if it is not renewed before the TTL expires.

For full info see https://www.consul.io/docs/internals/sessions.html[Consul Sessions internals]

The newly constructed session is provided with a named ID that can be used to identify it.
This ID can be used with the KV store to acquire locks: advisory mechanisms for mutual exclusion.

[source,java]
----
consulClient.createSessionWithOptions(opts, res -> {
  if (res.succeeded()) {
    System.out.println("Session successfully created");
    System.out.println("id: " + res.result());
  } else {
    res.cause().printStackTrace();
  }
});
----

And also to destroy it

[source,java]
----
consulClient.destroySession(sessionId, res -> {
  if (res.succeeded()) {
    System.out.println("Session successfully destroyed");
  } else {
    res.cause().printStackTrace();
  }
});
----

Lists sessions belonging to a node

[source,java]
----
consulClient.listNodeSessions("nodeId", res -> {
  if (res.succeeded()) {
    for(Session session: res.result().getList()) {
      System.out.println("Session id: " + session.getId());
      System.out.println("Session node: " + session.getNode());
      System.out.println("Session create index: " + session.getCreateIndex());
    }
  } else {
    res.cause().printStackTrace();
  }
});
----

All of the read session endpoints support blocking queries and all consistency modes.

[source,java]
----
BlockingQueryOptions blockingOpts = new BlockingQueryOptions()
  .setIndex(lastIndex);

consulClient.listSessionsWithOptions(blockingOpts, res -> {
  if (res.succeeded()) {
    System.out.println("Found " + res.result().getList().size() + " sessions");
  } else {
    res.cause().printStackTrace();
  }
});
----

== Nodes in datacenter

[source,java]
----
consulClient.catalogNodes(res -> {
  if (res.succeeded()) {
    System.out.println("found " + res.result().getList().size() + " nodes");
    System.out.println("consul state index " + res.result().getIndex());
  } else {
    res.cause().printStackTrace();
  }
});
----

This endpoint supports blocking queries and sorting by distance from specified node

[source,java]
----
NodeQueryOptions opts = new NodeQueryOptions()
  .setNear("_agent")
  .setBlockingOptions(new BlockingQueryOptions().setIndex(lastIndex));

consulClient.catalogNodesWithOptions(opts, res -> {
  if (res.succeeded()) {
    System.out.println("found " + res.result().getList().size() + " nodes");
  } else {
    res.cause().printStackTrace();
  }
});
----

== Prepared Queries

This endpoint creates, updates, destroys, and executes prepared queries.
Prepared queries allow you to register a complex service query and then execute it later via its ID
or name to get a set of healthy nodes that provide a given service. This is particularly useful in combination
with Consul's DNS Interface as it allows for much richer queries than would be possible given
the limited entry points exposed by DNS.

There are many parameters to creating a prepared query.
For full details please https://www.consul.io/api/query.html[see docs]

`dc` :: Specifies the datacenter to query. This will default to the datacenter of the agent being queried. This is specified as part of the URL as a query parameter.
`name` :: Specifies an optional friendly name that can be used to execute a query instead of using its ID.
`session` :: Specifies the ID of an existing session. This provides a way to automatically remove a prepared query when the given session is invalidated. If not given the prepared query must be manually removed when no longer needed.
`token` :: Specifies the ACL token to use each time the query is executed. This allows queries to be executed by clients with lesser or even no ACL Token, so this should be used with care. The token itself can only be seen by clients with a management token. If the Token field is left blank or omitted, the client's ACL Token will be used to determine if they have access to the service being queried. If the client does not supply an ACL Token, the anonymous token will be used.
`service` :: Specifies the name of the service to query. This is required field.
`failover` :: contains two fields, both of which are optional, and determine what happens if no healthy nodes are available in the local datacenter when the query is executed. It allows the use of nodes in other datacenters with very little configuration.
`nearestN` :: Specifies that the query will be forwarded to up to NearestN other datacenters based on their estimated network round trip time using Network Coordinates from the WAN gossip pool. The median round trip time from the server handling the query to the servers in the remote datacenter is used to determine the priority.
`datacenters` :: Specifies a fixed list of remote datacenters to forward the query to if there are no healthy nodes in the local datacenter. Datacenters are queried in the order given in the list. If this option is combined with NearestN, then the NearestN queries will be performed first, followed by the list given by Datacenters. A given datacenter will only be queried one time during a failover, even if it is selected by both NearestN and is listed in Datacenters.
`onlyPassing` :: Specifies the behavior of the query's health check filtering. If this is set to false, the results will include nodes with checks in the passing as well as the warning states. If this is set to true, only nodes with checks in the passing state will be returned.
`tags` :: Specifies a list of service tags to filter the query results. For a service to pass the tag filter it must have all of the required tags, and none of the excluded tags (prefixed with !).
`nodeMeta` :: Specifies a list of user-defined key/value pairs that will be used for filtering the query results to nodes with the given metadata values present.
`dnsTtl` :: Specifies the TTL duration when query results are served over DNS. If this is specified, it will take precedence over any Consul agent-specific configuration.
`templateType` :: is the query type, which must be `name_prefix_match`. This means that the template will apply to any query lookup with a name whose prefix matches the Name field of the template. In this example, any query for geo-db will match this query. Query templates are resolved using a longest prefix match, so it's possible to have high-level templates that are overridden for specific services. Static queries are always resolved first, so they can also override templates.
`templateRegexp` :: is an optional regular expression which is used to extract fields from the entire name, once this template is selected. In this example, the regular expression takes the first item after the "-" as the database name and everything else after as a tag. See the RE2 reference for syntax of this regular expression.

[source,java]
----
PreparedQueryDefinition def = new PreparedQueryDefinition()
  .setName("Query name")
  .setService("service-${match(1)}-${match(2)}")
  .setDcs(Arrays.asList("dc1", "dc42"))
  .setTemplateType("name_prefix_match")
  .setTemplateRegexp("^find_(.+?)_(.+?)$");
----

If the query is successfully created, its ID will be provided

[source,java]
----
consulClient.createPreparedQuery(def, res -> {
  if (res.succeeded()) {
    String queryId = res.result();
    System.out.println("Query created: " + queryId);
  } else {
    res.cause().printStackTrace();
  }
});
----

The prepared query can be executed by its id

[source,java]
----
consulClient.executePreparedQuery(id, res -> {
  if (res.succeeded()) {
    PreparedQueryExecuteResponse response = res.result();
    System.out.println("Found " + response.getNodes().size() + " nodes");
  } else {
    res.cause().printStackTrace();
  }
});
----

or by query string that must match template regexp

[source,java]
----
consulClient.executePreparedQuery("find_1_2", res -> {
  // matches template regexp "^find_(.+?)_(.+?)$"
  if (res.succeeded()) {
    PreparedQueryExecuteResponse response = res.result();
    System.out.println("Found " + response.getNodes().size() + " nodes");
  } else {
    res.cause().printStackTrace();
  }
});
----

Finally, `ConsulClient` allows you to modify, get or delete prepared queries

[source,java]
----
consulClient.deletePreparedQuery(query, res -> {
  if (res.succeeded()) {
    System.out.println("Query deleted");
  } else {
    res.cause().printStackTrace();
  }
});
----

== Watches

Watches are a way of specifying a view of data (e.g. list of nodes, KV pairs, health checks)
which is monitored for updates. When an update is detected, an `Handler` with `WatchResult` is invoked.
As an example, you could watch the status of health checks and notify when a check is critical.

[source,java]
----
Watch.key("foo/bar", vertx)
  .setHandler(res -> {
    if (res.succeeded()) {
      System.out.println("value: " + res.nextResult().getValue());
    } else {
      res.cause().printStackTrace();
    }
  })
  .start();
----