[[_writing_verticles]]
=== 编写 Verticle

Verticle 的实现类必须实现 `link:../../apidocs/io/vertx/core/Verticle.html[Verticle]` 接口。

如果您喜欢的话，可以直接实现该接口，但是通常直接从抽象类
`link:../../apidocs/io/vertx/core/AbstractVerticle.html[AbstractVerticle]` 继承更简单。

这儿有一个例子：

----
public class MyVerticle extends AbstractVerticle {

 // Verticle部署时调用
 public void start() {
 }

 // 可选 - Verticle撤销时调用
 public void stop() {
 }

}
----

通常您需要像上边例子一样重写 `start` 方法。

当 Vert.x 部署 Verticle 时，它的 `start` 方法将被调用，这个方法执行完成后 Verticle
就变成已启动状态。

您同样可以重写 `stop` 方法，当Vert.x 撤销一个 Verticle 时它会被调用，
这个方法执行完成后 Verticle 就变成已停止状态了。

[[_asynchronous_verticle_start_and_stop]]
=== Verticle 异步启动和停止

有些时候您的 Verticle 启动会耗费一些时间，您想要在这个过程做一些事，
并且您做的这些事并不想等到Verticle部署完成过后再发生。如：您想在 `start` 方法中部署其他的 Verticle。

您不能在您的 `start` 方法中阻塞等待其他的 Verticle 部署完成，这样做会破坏 <<golden_rule, Golden Rule>>。

所以您要怎么做？

您可以实现 *异步版本* 的 `start` 方法来实现，它接收一个 `Promise` 参数。
方法执行完时，Verticle 实例**并没有**部署好（状态不是 deployed）。

当所有您需要做的事（如：启动HTTP服务）完成后，就可以调用 `Future` 的 `complete`（或 `fail` ）
方法来标记启动完成或失败了。

这儿有一个例子：

----
public class MyVerticle extends AbstractVerticle {

 private HttpServer server;

 public void start(Promise<Void> startPromise) {
   server = vertx.createHttpServer().requestHandler(req -> {
     req.response()
       .putHeader("content-type", "text/plain")
       .end("Hello from Vert.x!");
     });

   // Now bind the server:
   server.listen(8080, res -> {
     if (res.succeeded()) {
       startPromise.complete();
     } else {
       startPromise.fail(res.cause());
     }
   });
 }
}
----

同样的，这儿也有一个异步版本的 `stop` 方法，如果您想做一些耗时的 Verticle清理工作，
您可以使用它。

----
public class MyVerticle extends AbstractVerticle {

 public void start() {
   // 做一些事
 }

 public void stop(Promise<Void> stopPromise) {
   obj.doSomethingThatTakesTime(res -> {
     if (res.succeeded()) {
       stopPromise.complete();
     } else {
       stopPromise.fail();
     }
   });
 }
}
----

NOTE: 在Verticle中启动的HTTP服务，无需在 `stop` 方法中手动停止；
Vert.x在撤销Verticle时会自动停止运行中的服务。
