= vertx-lang-kotlin-coroutines

`vertx-lang-kotlin-coroutines` 集成了 Kotlin _协程_ 以执行异步操作和处理事件。
以便在不阻塞内核线程的情况下使用类似顺序代码的编程模型。

[[_introduction]]
== 介绍

Vert.x 和许多经典应用平台的一个关键优势是它几乎是完全非阻塞的
(指内核线程)。
这允许基于 Vert.x 的应用程序使用极小数量的内核线程处理极高的并发（比如许多连接和消息），
这为强大的扩容能力扫除了障碍。

非阻塞的性质促生了异步的API，异步API存在很多种变种形式，比如 callbacks, promises, fibers 和 reactive 扩展。Vert.x对核心 API
使用了回调风格，但它也支持其他模型比如
RxJava 1 和 2。

在一些情况下，使用异步 API 编程要比使用经典的/顺序风格更加富有挑战性，
特别是当几个操作需要以顺序的形式完成时。
同理，当使用异步 API 时，错误传递通常也更加复杂。

`vertx-lang-kotlin-coroutines` 使用 _协程_。协程是一种非常轻量级的、不对应到内核线程的线程，
因此当一个_协程_需要“阻塞”时，它会_挂起_并释放当前的内核线程，
使另一个协程可以处理事件。

`vertx-lang-kotlin-coroutines` 使用 https://github.com/Kotlin/kotlinx.coroutines[kotlinx.coroutines] 来实现协程。

注意： `vertx-lang-kotlin-coroutines` 目前仅在 Kotlin 下工作，并且将在 Kotlin 1.3
脱离https://kotlinlang.org/docs/reference/coroutines.html#experimental-status-of-coroutines[实验]状态

[[_running_a_coroutine_from_a_vert_x_context]]
== 在 Vert.x 上下文中运行协程

导入 `io.vertx.kotlin.coroutines.VertxCoroutine` ，通过 `GlobalScope.launch` 方法可以在 "Global" 作用域中运行一个协程代码块，
（生命周期与应用一致）：

[source,kotlin,indent=0]
----
include::Example.kt[tags=launchCoroutine]
----

`vertx.dispatcher()` 返回了一个协程分发器，以便让协程运行在 Vert.x 的事件循环上。

`awaitEvent` 函数挂起了协程，当定时器超时时协程会通过被提供的 handler
恢复执行。
 with the value that was given to the handler.

下一章节会提供更多有关 handler, 事件和流事件的信息。

[[_extending_coroutineverticle]]
== 继承 CoroutineVerticle

你可以将代码部署为 `io.vertx.kotlin.coroutines.CoroutineVerticle` 的一个实例，它是专为 Kotlin 协程准备的一个特殊类型的 Verticle。
`CoroutineVerticle` 类实现了 `kotlinx.coroutines.experimental.CoroutineScope` 接口，所有协程构建器都默认绑定到 Verticle 的上下文。
应当重写 Verticle 中挂起的 `start()` 方法，重写挂起的 `stop()` 
方法是可选的：

[source,kotlin,indent=0]
----
include::Example.kt[tags=CoroutineVerticle]
----

以上所有的代码都假设被运行在一个 `CoroutineVerticle` 实现中，但是也可以通过替换所有的 `<builder> { .. }` 为
`GlobalScope.<builder> { .. }` 来使用应用作用域。

[[_getting_one_shot_asynchronous_results]]
== 单次获取异步执行的结果

Vert.x 中的许多异步操作的最后一个参数是一个 `Handler<AsyncResult<T>>`。
比如在通过 Vert.x Mongo 客户端获取一个对象，或者在事件总线上发送一条消息并等待回复的时候。

可以通过 `awaitResult` 方法来返回值或者抛出一个异常。

协程将被挂起直到事件被处理，内核线程不会被阻塞。

该方法通过指定一个会在运行时被传入 handler 的异步操作代码块来运行。

示例如下：

[source,kotlin,indent=0]
----
include::Example.kt[tags=awaitResult]
----

当块中的代码产生了一个失败是时，调用者可以通过
`try`/`catch` 结构像处理一个普通的异常一样进行处理。
`try`/`catch` constructs:

[source,kotlin,indent=0]
----
include::Example.kt[tags=awaitResultFailure]
----

[[_getting_one_shot_events]]
== 获取获取事件

单次处理事件（如果该事件再次产生，不会再进行处理）可以使用函数 `awaitEvent` ：

[source,kotlin,indent=0]
----
include::Example.kt[tags=awaitEvent]
----

[[_getting_one_shot_worker_results]]
== 单次获取 worker 结果

处理阻塞计算的结果可以使用函数 `awaitBlocking` ：

[source,kotlin,indent=0]
----
include::Example.kt[tags=awaitBlocking]
----

[[_streams_of_events]]
== 事件流

Vert.x API 有许多地方使用 handlers 处理事件流。
以下示例包含了处理事件总线消息和 HTTP 服务请求。

`ReceiveChannelHandler` 类允许通过（可挂起的） `receive` 方法接收事件：

[source,kotlin,indent=0]
----
include::Example.kt[tags=streamExample]
----

[[_awaiting_the_completion_of_vert_x_asynchronous_results]]
== 获取 Vert.x 异步操作的完成结果

Vert.x 4 提供了 future 模型并且 `Future` 有个 `await()` 可挂起方法用于异步获取结果。

Vert.x 异步结果实例上的 `await` 扩展方法挂起协程直到异步操作完成，并返回一个关联的 `AsyncResult<T>` 对象。

[source,kotlin,indent=0]
----
include::Example.kt[tags=awaitingFuture]
----

[[_suspending_extension_methods]]
== 挂起方法扩展

为了简化使用 Vert.x 异步 API 的协程编写，Vert.x 3 生成了扩展方法。
它让用户不必使用 `awaitResult` ，这使得代码更加简洁和可读。

由于 Vert.x 4 提供了基于 future 的 API，那些扩展方法仍会存在，但将被_弃用_。

[source,kotlin,indent=0]
----
include::Example.kt[tags=generatedSuspendingExtensionMethod]
----

[[_channels]]
== 通道

通道接近 Java 的 `BlockingQueue`，不同之处在于它不是阻塞的，而是在如下情况中挂起协程：

- 向一个满了的通道中写入值
- 从一个空的通道中读取值

可以通过使用 `toChannel` 扩展方法使 Vert.x 的 `ReadStream` 和 `WriteStream` 适配到通道

这些适配器将会管理背压和流终止

* `ReadStream<T>` 适配到 `ReceiveChannel<T>`
* `WriteStream<T>` 适配到 `SendChannel<T>`

[[_receiving_data]]
=== 接收数据

当需要处理流中互相关联的值时，通道真的很有用：

[source,kotlin,indent=0]
----
include::Example.kt[tags=channel0]
----

还有一个很有用的场景是解析协议时，我们将构建一个非阻塞的 HTTP 请求解析器来展示通道的强大。

我们将依靠 http://vertx.io/docs/apidocs/io/vertx/core/parsetools/RecordParser.html[`RecordParser`] 来根据 `\r\n` 切分缓冲流。

如下是一个初始版本的解析器，只处理 HTTP 的请求行

[source,kotlin,indent=0]
----
include::Example.kt[tags=channel1]
----

解析请求行只需简单地在通道上调用 `receive`。

接下来接收分片并解析 HTTP 头，直到遇到一个空白行。

[source,kotlin,indent=0]
----
include::Example.kt[tags=channel2]
----

最终终止解析器来处理一个可选的请求体

[source,kotlin,indent=0]
----
include::Example.kt[tags=channel3]
----

[[_sending_data]]
=== 发送数据

使用通道发送数据非常简单清晰：

[source,kotlin,indent=0]
----
include::Example.kt[tags=sendChannel]
----

Both `SendChannel#send` and `WriteStream#write` are non blocking operations, however unlike `SendChannel#send`
can suspend the execution when the channel is full, the equivalent without a channel would look like
`SendChannel#send` 和 `WriteStream#write` 都是非阻塞操作，然而不同于 `SendChannel#send` 可以在通道满时暂停执行，不使用通道的情况看起来像

[source,kotlin,indent=0]
----
include::Example.kt[tags=sendChannel]
----

[[_delay_cancellation_and_timeouts]]
== 延迟，取消和超时

Vertx 分发器通过定时器为协程的 `delay` 函数提供完整的支持：

[source,kotlin,indent=0]
----
include::Example.kt[tags=delay]
----

定时器支持取消

[source,kotlin,indent=0]
----
include::Example.kt[tags=cancellation]
----

取消是https://github.com/Kotlin/kotlinx.coroutines/blob/master/coroutines-guide.md#cancellation-is-cooperative[协作的]

也可以使用 `withTimeout` 计划一个超时值

[source,kotlin,indent=0]
----
include::Example.kt[tags=withTimeout]
----

[[_coroutine_builders]]
== 协程构建器

Vert.x 适用于任何协程构建器，只要 `CoroutineScope` 实例是有效的：`launch`, `async`, `produce', ... . 一下重要事项必须被注意：

- `runBlocking` 没有 `CoroutineScope` 因此禁止在 Vert.x 事件循环线程上只用。
- The `runBlocking` doesn't need a `CoroutineScope` and must not be used from a Vert.x event loop thread.
- 为避免内存泄漏，总是使用 `coroutineScope {..}` 定义一个子作用域。在这种情况下，如果一个作用域中的协程失败，所有在该作用域中的协程都会被取消

[[_coroutine_interoperability]]
== 协程互操作性

Vert.x 集成被设计成完全与 Kotlin 协程互操作的

* `kotlinx.coroutines.experimental.sync.Mutex` are executed on the event loop thread when using the vertx dispatcher
* 当使用 vertx 分发器时，`kotlinx.coroutines.experimental.sync.Mutex` 在事件循环线程上执行

[[_rxjava_interoperability]]
== RxJava 互操作性

模块 `vertx-lang-kotlin-coroutines` 没有与 RxJava 的特定集成，然而 Kotlin 协程提供了 RxJava 的集成，它与 `vertx-lang-kotlin-coroutines` 一同工作良好。

可以在这里了解更多：https://github.com/Kotlin/kotlinx.coroutines/blob/master/reactive/coroutines-guide-reactive.md[Guide to reactive streams with coroutines]