[[_infinispan_web_session_store]]
= Infinispan 网络会话存储

依赖于 https://infinispan.org/[Infinispan] Java 客户端的一种 `link:../../apidocs/io/vertx/ext/web/sstore/SessionStore.html[SessionStore]` 实现。

WARNING: 此模块具有 _Tech Preview_ 状态，这意味着 API 可能会在后续版本中更改。

[[_getting_started]]
== 由此开始

要使用此模块，请将以下内容添加到 Maven POM 文件的 _dependencies_ 部分中：

[source,xml,subs="+attributes"]
----
<dependency>
 <groupId>io.vertx</groupId>
 <artifactId>vertx-web-sstore-infinispan</artifactId>
 <version>4.3.0</version>
</dependency>
----

或者，您使用的是 Gradle：

[source,groovy,subs="+attributes"]
----
compile 'io.vertx:vertx-web-sstore-infinispan:4.3.0'
----

[[_using]]
== 使用

如果这个会话存储是您所有依赖项中唯一的一项，那么您可以用一种通用的方式将其初始化：

[source,java]
----
JsonObject config = new JsonObject()
  .put("servers", new JsonArray()
    .add(new JsonObject()
      .put("host", "server1.datagrid.mycorp.int")
      .put("username", "foo")
      .put("password", "bar"))
    .add(new JsonObject()
      .put("host", "server2.datagrid.mycorp.int")
      .put("username", "foo")
      .put("password", "bar"))
  );
SessionStore store = SessionStore.create(vertx, config);
SessionHandler sessionHandler = SessionHandler.create(store);
router.route().handler(sessionHandler);
----

或者，使用明确的 `link:../../apidocs/io/vertx/ext/web/sstore/infinispan/InfinispanSessionStore.html[InfinispanSessionStore]` 类型。

[source,java]
----
JsonObject config = new JsonObject()
  .put("servers", new JsonArray()
    .add(new JsonObject()
      .put("host", "server1.datagrid.mycorp.int")
      .put("username", "foo")
      .put("password", "bar"))
    .add(new JsonObject()
      .put("host", "server2.datagrid.mycorp.int")
      .put("username", "foo")
      .put("password", "bar"))
  );
InfinispanSessionStore store = InfinispanSessionStore.create(vertx, config);
SessionHandler sessionHandler = SessionHandler.create(store);
router.route().handler(sessionHandler);
----

[[_configuring]]
== 配置

[[_config_entries]]
=== 配置条目（entry）

根条目是：

* `servers`：强制/必填的，服务器定义的 JSON 数组（见下文）
* `cacheName`：可选的，用于存储会话数据的缓存名称（默认为 `vertx-web.sessions`）
* `retryTimeout`：可选的，会话处理程序从存储中检索值时所使用的重试超时时间（以毫秒为单位）（`5000`）

用于服务器定义的条目是：

* `uri` ：可选的，一个 https://infinispan.org/blog/2020/05/26/hotrod-uri/[Hot Rod URI]
* `host`：可选的（默认为 `localhost`）
* `port`：可选的（默认为 `11222`）
* `clientIntelligence`：可选的（以下值之一 `BASIC`，`TOPOLOGY_AWARE`，`HASH_DISTRIBUTION_AWARE`）
* `username`：强制的
* `password`：强制的
* `realm`：可选的（默认为 `default`）
* `saslMechanism`：可选的（默认为 `DIGEST-MD5`）
* `saslQop`：可选的（以下值之一 `AUTH`，`AUTH_INT`，`AUTH_CONF`）

IMPORTANT: 如果设置了 `uri` 条目，则其他条目将被忽略。

[[_custom_infinispan_client]]
=== 自定义 Infinispan 客户端

对于高级配置要求，
您可以提供自定义的 https://docs.jboss.org/infinispan/12.1/apidocs/org/infinispan/client/hotrod/RemoteCacheManager.html[`RemoteCacheManager`]：

[source,java]
----
InfinispanSessionStore sessionStore = InfinispanSessionStore.create(vertx, config, remoteCacheManager);
----
