[[_using_transactions]]
== 使用事务

[[_transactions_with_connections]]
=== 连接中使用事务操作

您可以使用SQL语法 `BEGIN`/`COMMIT`/`ROLLBACK` 来执行事务操作，同时您必须使用
`link:../../apidocs/io/vertx/sqlclient/SqlConnection.html[SqlConnection]` 并自己管理当前连接。

或者您也可以使用 `link:../../apidocs/io/vertx/sqlclient/SqlConnection.html[SqlConnection]` 的事务API：

[source,java]
----
pool.getConnection()
  // Transaction must use a connection
  .onSuccess(conn -> {
    // Begin the transaction
    conn.begin()
      .compose(tx -> conn
        // Various statements
        .query("INSERT INTO Users (first_name,last_name) VALUES ('Julien','Viet')")
        .execute()
        .compose(res2 -> conn
          .query("INSERT INTO Users (first_name,last_name) VALUES ('Andy','Guibert')")
          .execute())
        // Commit the transaction
        .compose(res3 -> tx.commit()))
      // Return the connection to the pool
      .eventually(v -> conn.close())
      .onSuccess(v -> System.out.println("Transaction succeeded"))
      .onFailure(err -> System.out.println("Transaction failed: " + err.getMessage()));
  });
----

当数据库服务端返回当前事务已失败（比如常见的 _current transaction is aborted, commands ignored until end of transaction block_）
，事务已回滚和 `link:../../apidocs/io/vertx/sqlclient/Transaction.html#completion--[completion]` 方法的返回值future返回了
`link:../../apidocs/io/vertx/sqlclient/TransactionRollbackException.html[TransactionRollbackException]` 异常时：

[source,java]
----
tx.completion()
  .onFailure(err -> {
    System.out.println("Transaction failed => rolled back");
  });
----

[[_simplified_transaction_api]]
=== 简化版事务API

当您使用连接池时，您可以调用 `link:../../apidocs/io/vertx/sqlclient/Pool.html#withTransaction-java.util.function.Function-io.vertx.core.Handler-[withTransaction]` 方法
并传递待执行的事务操作作为参数。

这将会从连接池里拿到一条连接，开启事务并调用待执行操作，配合客户端一起执行该事务范围内
的所有操作。

待执行操作需要返回一个future来表示可能产生的结果：

- 当future成功时，客户端提交该事务
- 当future失败时，客户端回滚该事务

事务操作完成后，连接会被释放回连接池，并且可以获取到最终的操作结果。

[source,java]
----
pool.withTransaction(client -> client
  .query("INSERT INTO Users (first_name,last_name) VALUES ('Julien','Viet')")
  .execute()
  .flatMap(res -> client
    .query("INSERT INTO Users (first_name,last_name) VALUES ('Andy','Guibert')")
    .execute()
    // Map to a message result
    .map("Users inserted")))
  .onSuccess(v -> System.out.println("Transaction succeeded"))
  .onFailure(err -> System.out.println("Transaction failed: " + err.getMessage()));
----
