= Vert.x Kafka Admin Client
:toc: left
:lang: java
:java: java

该组件提供了对 Kafka 管理客户端接口的 Vert.x 风格的包装。
Kafka 管理客户端用于创建，修改和删除主题。
除此之外，它还可以用于管理 ACL (Access Control Lists)，消费者群组和更多信息。

== 创建 Kafka 管理客户端

创建 Kafka 管理客户端的方法与使用原生 Kafka 客户端库十分相似。

您需要配置一些属性，这些属性可以参见官方的
Apache Kafka 文档， 参考此链接:https://kafka.apache.org/documentation/#adminclientconfigs[admin].

为了传递配置信息，您可以使用一个 Map 来保存属性值，
并在调用 `link:../../apidocs/io/vertx/kafka/admin/KafkaAdminClient.html[KafkaAdminClient]` 提供的静态创建方法传入。

[source,java]
----
Properties config = new Properties();
config.put(AdminClientConfig.BOOTSTRAP_SERVERS_CONFIG, "localhost:9092");

KafkaAdminClient adminClient = KafkaAdminClient.create(vertx, config);
----

== 使用 Kafka 管理客户端

=== 获取主题列表

您可以调用 `link:../../apidocs/io/vertx/kafka/admin/KafkaAdminClient.html#listTopics-io.vertx.core.Handler-[listTopics]` 方法来获取集群中的主题列表。
该方法唯一需要的参数是一个回调函数用于处理返回的主题列表。

[source,java]
----
adminClient.listTopics().onSuccess(topics ->
    System.out.println("Topics= " + topics)
);
----

=== 主题描述

您可以调用 `link:../../apidocs/io/vertx/kafka/admin/KafkaAdminClient.html#describeTopics-java.util.List-io.vertx.core.Handler-[describeTopics]` 方法来获取集群中的主题描述。
主题描述是指获取该主题相关的元数据，例如分片数量，副本，领导，同步中的副本等。
方法需要的参数是您要获取的主题列表和用于处理结果的回调，
回调会通过一个 Map 来返回查询结果，Map 的键是主题名称，Map 的内容是 `link:../../apidocs/io/vertx/kafka/admin/TopicDescription.html[TopicDescription]`。

[source,java]
----
adminClient.describeTopics(Collections.singletonList("my-topic")).onSuccess(topics -> {
  TopicDescription topicDescription = topics.get("first-topic");

  System.out.println("Topic name=" + topicDescription.getName() +
      " isInternal= " + topicDescription.isInternal() +
      " partitions= " + topicDescription.getPartitions().size());

  for (TopicPartitionInfo topicPartitionInfo : topicDescription.getPartitions()) {
    System.out.println("Partition id= " + topicPartitionInfo.getPartition() +
      " leaderId= " + topicPartitionInfo.getLeader().getId() +
      " replicas= " + topicPartitionInfo.getReplicas() +
      " isr= " + topicPartitionInfo.getIsr());
  }
});
----

=== 创建主题

您可以调用 `link:../../apidocs/io/vertx/kafka/admin/KafkaAdminClient.html#createTopics-java.util.List-io.vertx.core.Handler-[createTopics]` 方法在集群中创建主题，
方法需要的参数是您要创建的主题列表和处理结果的回调。
要创建的主题需要通过 `link:../../apidocs/io/vertx/kafka/admin/NewTopic.html[NewTopic]` 类来指定名称
分区的数量和复制因子。
也可以指定副本的分配，将副本映射给每个 Kafka 消息中介的 id，而不是仅设置
分片的数量和复制银子 (在这种情况下该值会被设置为 -1)。

[source,java]
----
adminClient.createTopics(Collections.singletonList(new NewTopic("testCreateTopic", 1, (short)1)))
  .onSuccess(v -> {
    // 成功创建主题
  })
  .onFailure(cause -> {
    // 创建主题时出错
  });
----

=== 删除主题

您可以调用 `link:../../apidocs/io/vertx/kafka/admin/KafkaAdminClient.html#deleteTopics-java.util.List-io.vertx.core.Handler-[deleteTopics]` 方法来删除集群中的主题。
方法需要的参数是要删除的主题列表和处理结果的回调。

[source,java]
----
adminClient.deleteTopics(Collections.singletonList("topicToDelete"))
  .onSuccess(v -> {
    // 成功删除主题
  })
  .onFailure(cause -> {
    // 删除主题时出错
  });
----

=== 配置描述

您可以调用 `link:../../apidocs/io/vertx/kafka/admin/KafkaAdminClient.html#describeConfigs-java.util.List-io.vertx.core.Handler-[describeConfigs]` 方法来获取资源配置的数据。
资源配置的描述是指获取集群中一些资源的信息，例如主题和消息中介。
方法需要的参数是您想要获取的资源列表和用于处理结果的回调。
资源配置通过一个类型为 `link:../../apidocs/io/vertx/kafka/client/common/ConfigResource.html[ConfigResource]` 的集合描述。每个配置的数据
保存在 `link:../../apidocs/io/vertx/kafka/admin/Config.html[Config]` 类的 `link:../../apidocs/io/vertx/kafka/admin/ConfigEntry.html[ConfigEntry]`
键值对类型中

[source,java]
----
adminClient.describeConfigs(Collections.singletonList(
  new ConfigResource(org.apache.kafka.common.config.ConfigResource.Type.TOPIC, "my-topic"))).onSuccess(configs -> {
  // 检查配置
});
----

=== 选择配置

您可以调用 `link:../../apidocs/io/vertx/kafka/admin/KafkaAdminClient.html#alterConfigs-java.util.Map-io.vertx.core.Handler-[alterConfigs]` 方法来选取集群的资源配置。
选取资源配置是指更新集群资源的配置信息，例如主题和分区。
方法需要的参数是您想更新的配置的资源列表和用于处理结果的回调。
您可以在一次方法调用中选取更新多个不同资源的数据。需要的参数是
`link:../../apidocs/io/vertx/kafka/client/common/ConfigResource.html[ConfigResource]` 作为资源参数与 `link:../../apidocs/io/vertx/kafka/admin/Config.html[Config]` 作为配置一一对应。

[source,java]
----
ConfigResource resource = new ConfigResource(org.apache.kafka.common.config.ConfigResource.Type.TOPIC, "my-topic");
// 创建更新该主题 retention.ms 的配置项
ConfigEntry retentionEntry = new ConfigEntry(TopicConfig.RETENTION_MS_CONFIG, "51000");
Map<ConfigResource, Config> updateConfig = new HashMap<>();
updateConfig.put(resource, new Config(Collections.singletonList(retentionEntry)));
adminClient.alterConfigs(updateConfig)
  .onSuccess(v -> {
    // 成功更新配种
  })
  .onFailure(cause -> {
    // 配置更新时出错
  });
----

=== 消费者群组列表

您可以调用 `link:../../apidocs/io/vertx/kafka/admin/KafkaAdminClient.html#listConsumerGroups-io.vertx.core.Handler-[listConsumerGroups]` 方法来获取集群中的消费者群组列表。
方法需要的参数只有用于处理消费者群组列表结果的回调。

[source,java]
----
adminClient.listConsumerGroups().onSuccess(consumerGroups ->
  System.out.println("ConsumerGroups= " + consumerGroups)
);
----

=== 消费者群组的描述

您可以调用 `link:../../apidocs/io/vertx/kafka/admin/KafkaAdminClient.html#describeConsumerGroups-java.util.List-io.vertx.core.Handler-[describeConsumerGroups]` 来获取消费者群组的描述。
消费者群组的描述是指获取消费者群组的相关信息，例如成员，相关的 id，主题订阅，分区分配等。
需要的参数是要获取描述的消费者群组列表和用于处理结果的回调，
回调会通过一个 Map 来返回查询结果，Map 的键是消费者群组的名称，Map 的值类型是 `link:../../apidocs/io/vertx/kafka/admin/MemberDescription.html[MemberDescription]` 。

[source,java]
----
adminClient.describeTopics(Collections.singletonList("my-topic")).onSuccess(topics -> {
  TopicDescription topicDescription = topics.get("first-topic");

  System.out.println("Topic name=" + topicDescription.getName() +
      " isInternal= " + topicDescription.isInternal() +
      " partitions= " + topicDescription.getPartitions().size());

  for (TopicPartitionInfo topicPartitionInfo : topicDescription.getPartitions()) {
    System.out.println("Partition id= " + topicPartitionInfo.getPartition() +
      " leaderId= " + topicPartitionInfo.getLeader().getId() +
      " replicas= " + topicPartitionInfo.getReplicas() +
      " isr= " + topicPartitionInfo.getIsr());
  }
});
----