[[_record_parser]]
== 记录解析器（Record Parser）

记录解析器（Record Parser）允许您轻松解析由字节序列分割的协议，或者固定长度的协议。
它将输入缓冲区序列转换为按照配置重组后的缓冲区序列
（固定大小或带分隔符的记录）。

例如，若您使用 `\n` 分割的简单ASCII文本协议，并输入如下：

[source]
----
buffer1:HELLO\nHOW ARE Y
buffer2:OU?\nI AM
buffer3: DOING OK
buffer4:\n
----

记录解析器将生成下结果：
[source]
----
buffer1:HELLO
buffer2:HOW ARE YOU?
buffer3:I AM DOING OK
----

我们来看看相关代码：

[source, java]
----
final RecordParser parser = RecordParser.newDelimited("\n", h -> {
  System.out.println(h.toString());
});

parser.handle(Buffer.buffer("HELLO\nHOW ARE Y"));
parser.handle(Buffer.buffer("OU?\nI AM"));
parser.handle(Buffer.buffer("DOING OK"));
parser.handle(Buffer.buffer("\n"));
----

我们还可以生成固定长度的块，如下：

[source, java]
----
RecordParser.newFixed(4, h -> {
  System.out.println(h.toString());
});
----

有关更多详细信息，请查看 `link:../../apidocs/io/vertx/core/parsetools/RecordParser.html[RecordParser]` 类。

[[_json_parser]]
== Json 解析器

解析JSON结构很容易，但这要求你一次性提供完整的JSON，
而对于非常大的JSON结构，则并不是特别适合使用JSON解析器来处理。

非阻塞JSON解析器 则是一个事件驱动的解析器, 它可以处理体积非常大的JSON。
它会将一系列输入的buffer转换为一系列的JSON解析器事件。

[source, java]
----
JsonParser parser = JsonParser.newParser();

// 设置不同事件的handler
parser.handler(event -> {
  switch (event.type()) {
    case START_OBJECT:
      // Json对象的开始
      break;
    case END_OBJECT:
      // Json对象的结束
      break;
    case START_ARRAY:
      // Json数组的开始
      break;
    case END_ARRAY:
      // Json数组的结束
      break;
    case VALUE:
      // 处理一个取值
      String field = event.fieldName();
      if (field != null) {
        // 当前处于Json对象内
      } else {
        // 当前处于Json数组内，或Json最顶层
        if (event.isString()) {

        } else {
          // ...
        }
      }
      break;
  }
});
----

该解析器是非阻塞的，并且事件由输入的buffer来驱动触发。

[source, java]
----
JsonParser parser = JsonParser.newParser();

// start array event
// start object event
// "firstName":"Bob" event
parser.handle(Buffer.buffer("[{\"firstName\":\"Bob\","));

// "lastName":"Morane" event
// end object event
parser.handle(Buffer.buffer("\"lastName\":\"Morane\"},"));

// start object event
// "firstName":"Luke" event
// "lastName":"Lucky" event
// end object event
parser.handle(Buffer.buffer("{\"firstName\":\"Luke\",\"lastName\":\"Lucky\"}"));

// end array event
parser.handle(Buffer.buffer("]"));

// Always call end
parser.end();
----

事件驱动的解析过程提供了更多的控制能力，同时带来了“需要处理细粒度事件”的缺点，有时候不太方便。
当你需要的时候，JSON解析器允许你将JSON结构作为值处理。

[source, java]
----
JsonParser parser = JsonParser.newParser();

parser.objectValueMode();

parser.handler(event -> {
  switch (event.type()) {
    case START_ARRAY:
      // Start the array
      break;
    case END_ARRAY:
      // End the array
      break;
    case VALUE:
      // Handle each object
      break;
  }
});

parser.handle(Buffer.buffer("[{\"firstName\":\"Bob\"},\"lastName\":\"Morane\"),...]"));
parser.end();
----

`value-mode` 可以在解析过程中启用或停用，
允许你在细粒度事件与JSON对象事件之间自由切换。

[source, java]
----
JsonParser parser = JsonParser.newParser();

parser.handler(event -> {
  // Start the object

  switch (event.type()) {
    case START_OBJECT:
      // 设置为 value-mode，自此开始，解析器则不会触发start-object事件
      parser.objectValueMode();
      break;
    case VALUE:
      // 处理每一个对象
      // 获得从对象中解析出来的字段
      String id = event.fieldName();
      System.out.println("User with id " + id + " : " + event.value());
      break;
    case END_OBJECT:
      // 设置为 event mode，所以解析器重新触发 start/end 事件
      parser.objectEventMode();
      break;
  }
});

parser.handle(Buffer.buffer("{\"39877483847\":{\"firstName\":\"Bob\"},\"lastName\":\"Morane\"),...}"));
parser.end();
----

你也可以对数组做同样的事情

[source, java]
----
JsonParser parser = JsonParser.newParser();

parser.handler(event -> {
  // Json对象的开始

  switch (event.type()) {
    case START_OBJECT:
      // 设置为value mode来处理每个元素，自此开始，解析器不会触发 start-array 事件
      parser.arrayValueMode();
      break;
    case VALUE:
      // 处理每一个数组
      // 获取对象中的字段
      System.out.println("Value : " + event.value());
      break;
    case END_OBJECT:
      // 设置为 event mode，从而解析器会重新触发 start/end 事件
      parser.arrayEventMode();
      break;
  }
});

parser.handle(Buffer.buffer("[0,1,2,3,4,...]"));
parser.end();
----

你也可以解码为POJO。

[source, java]
----
parser.handler(event -> {
  // 获取每个对象
  // 获取对象中的字段
  String id = event.fieldName();
  User user = event.mapTo(User.class);
  System.out.println("User with id " + id + " : " + user.firstName + " " + user.lastName);
});
----

解析器解析buffer失败之后，会抛出异常；也可以通过设置 `exception handler` 处理异常：

[source, java]
----
JsonParser parser = JsonParser.newParser();

parser.exceptionHandler(err -> {
  // 捕捉所有的解析/解码异常
});
----

解析器也可以解析JSON流：

- 连续的JSON流： `{"temperature":30}{"temperature":50}`
- 行分割的JSON流： `{"an":"object"}\r\n3\r\n"a string"\r\nnull`

更多细节，详见 `link:../../apidocs/io/vertx/core/parsetools/JsonParser.html[JsonParser]` 。
