= Vert.x Json Schema
:toc: left

Vert.x Json Schema组件提供了一个异步可扩展的 https://json-schema.org/[Json Schema] 规范实现。
你可以使用 Json Schema 去校验每一个json结构的数据。这个组件提供以下特性：

* 实现了 https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-validation-00[draft 2020-12]
* 实现了 https://datatracker.ietf.org/doc/html/draft-handrews-json-schema-validation-02[draft 2019-09]
* 实现了 https://datatracker.ietf.org/doc/html/draft-handrews-json-schema-validation-01[draft 7]
* 实现了 https://datatracker.ietf.org/doc/html/draft-fge-json-schema-validation-00[draft 4]
* Dereferencing of `$ref` resolution and caching
* 通过DSL来构建schemas

[[_using_vert_x_json_schema]]
== 使用 Vert.x Json Schema

为了使用 Vert.x Json Schema ，需要在构建配置文件中添加如下 _依赖_：

* Maven （在 `pom.xml` 文件中）：

[source,xml,subs="+attributes"]
----
<dependency>
 <groupId>io.vertx</groupId>
 <artifactId>vertx-json-schema</artifactId>
 <version>4.3.0</version>
</dependency>
----

* Gradle （在 `build.gradle` 文件中）：

[source,groovy,subs="+attributes"]
----
dependencies {
 compile 'io.vertx:vertx-json-schema:4.3.0'
}
----

[[_concepts]]
== 相关概念

=== JsonSchema

Schemas can exist in 2 flavours:

* JSON as in JSON natation
* Boolean as in `true/false`

The `link:../../apidocs/io/vertx/json/schema/JsonSchema.html[JsonSchema]` interface allows both types to be handled without the constant check of the
underlying type.

=== SchemaRepository

The `link:../../apidocs/io/vertx/json/schema/SchemaRepository.html[SchemaRepository]` holds `link:../../apidocs/io/vertx/json/schema/JsonSchema.html[JsonSchema]` instances. It performs
dereferencing of schemas to speed up validation. The repository is a simple key store, this means that it does not allow
duplicate ids.

The repository can then create `link:../../apidocs/io/vertx/json/schema/Validator.html[Validator]` instances aware of all sub schemas in the
repository.

=== Validator

As the name implies the `link:../../apidocs/io/vertx/json/schema/Validator.html[Validator]` validates an object using a start schema. The output
format is dependent of the configuration.

[[_parse_a_schema]]
== 解析schema

When working with multiple schemas or sub-schemas, it is recommended to use a `Repository`.

To parse a schema you first need a `JsonSchema` and some initial configuration. Since schemas can contain references it
is required for the validator and repository to be aware of your application `baseUri`. This allows you to reference your
own schemas in other sub-schemas. For the purpose of dereferencing, you don't need to configure a draft.

[source,java]
----
SchemaRepository repository =
  SchemaRepository.create(new JsonSchemaOptions().setBaseUri("https://vertx.io"));
----

You can use `JsonSchema` instances for different `Validator` and you can parse different `JsonSchema` with `JsonParser`
directly.

现在你可以解析schema了：

[source,java]
----
JsonSchema schema = JsonSchema.of(object);

// Or

repository.dereference(JsonSchema.of(object));
----

[IMPORTANT]
====
Remember that for security reasons, this module will not attempt to download any referenced sub-schema. All required
sub-schemas should be provided to a repository object.
====

[[_validate]]
== 校验

Given the dynamic nature of json-schema and the conditional `if-then-else` it is not possible to validate in a streaming
scenario. Validation is for this reason a blocking operation. If you are aware that validation will be a very expensive
process, then it is advisable to run the validation on a dedicated thread pool or using `executeBlocking`.
A schema could have two states:

To validate a schema:

[source,java]
----
OutputUnit result = Validator.create(
    schema,
    new JsonSchemaOptions().setDraft(Draft.DRAFT7))
  .validate(json);

if (result.getValid()) {
  // Successful validation
}
----

== Custom formats

Adding custom formats is not allowed. This may sound like a limitation but it arises from the validation spec.
Validators are expected to assume unknown formats as valid input, delegating to the application business code the role
of validator for custom values.

[[_building_your_schemas_from_code]]
== 用代码来构建schema

如果你想要使用代码来构建schema，你可以使用附带的DSL。目前只有Draft-7支持这个特性。

首先，通过静态导入（import static） `link:../../apidocs/io/vertx/json/schema/draft7/dsl/Schemas.html[Schemas]` 和 `link:../../apidocs/io/vertx/json/schema/draft7/dsl/Keywords.html[Keywords]` 。

[[_creating_the_schema]]
=== 创建schema

在 `link:../../apidocs/io/vertx/json/schema/draft7/dsl/Schemas.html[Schemas]` 内部提供了schema创建的静态方法：

[source,java]
----
SchemaBuilder intSchemaBuilder = intSchema();
SchemaBuilder objectSchemaBuilder = objectSchema();
----

[[_using_the_keywords]]
=== 使用关键词

对于每一个schema，你是否可以使用 `link:../../apidocs/io/vertx/json/schema/draft7/dsl/Keywords.html[Keywords]` 方法来构建关键词，
这取决于schema的类型：

[source,java]
----
stringSchema()
  .with(format(StringFormat.DATETIME));
arraySchema()
  .with(maxItems(10));
schema() // 生成同时接收数组和整数的schema
  .with(type(SchemaType.ARRAY, SchemaType.INT));
----

[[_defining_the_schema_structure]]
=== 定义schema的结构

根据你创建的schema，你可以定义结构。

使用属性schema和其他属性schema来创建一个对象类型的schema：

[source,java]
----
objectSchema()
  .requiredProperty("name", stringSchema())
  .requiredProperty("age", intSchema())
  .additionalProperties(stringSchema());
----

创建一个数组类型的schema：

[source,java]
----
arraySchema()
  .items(stringSchema());
----

创建元组类型的schema：

[source,java]
----
tupleSchema()
  .item(stringSchema()) // 第一个元素
  .item(intSchema()) // 第二个元素
  .item(booleanSchema()); // 第三个元素
----

[[_ref_and_aliases]]
=== `$ref` 和 别名

你可以使用 `link:../../apidocs/io/vertx/json/schema/common/dsl/Schemas.html#ref-io.vertx.core.json.pointer.JsonPointer-[Schemas.ref]` 方法来添加一个 `$ref` schema。
通过 `link:../../apidocs/io/vertx/json/schema/common/dsl/SchemaBuilder.html#id-io.vertx.core.json.pointer.JsonPointer-[id]` 来指定对应schema的 `$id` 关键词。

你也可以使用别名来引用通过dsl定义的schema。你可以使用 `link:../../apidocs/io/vertx/json/schema/common/dsl/SchemaBuilder.html#alias-java.lang.String-[alias]` 来为一个schema设置别名。
这样你就可以使用 `link:../../apidocs/io/vertx/json/schema/common/dsl/Schemas.html#refToAlias-java.lang.String-[Schemas.refToAlias]` 来根据别名引用schema。

[source,java]
----
intSchema()
  .alias("myInt");

objectSchema()
  .requiredProperty("anInteger", refToAlias("myInt"));
----

[[_using_the_schema]]
=== 使用schema

After you defined the schema, you can call `link:../../apidocs/io/vertx/json/schema/common/dsl/SchemaBuilder.html#toJson--[toJson]` to return the JSON notation of the schema:

[source,java]
----
JsonObject schema = objectSchema()
  .requiredProperty("name", stringSchema())
  .requiredProperty("age", intSchema())
  .additionalProperties(stringSchema())
  .toJson();
----
