[[_buffers]]
== Buffers
:toc: left

在 Vert.x 内部，大部分数据被重新组织（shuffle，表意为洗牌）成 `Buffer` 格式。

`Buffer` 是一个可以被读取或写入的，包含0个或多个字节的序列，并且能够根据写入的字节自动扩容。
您也可以将 `Buffer` 想象成一个智能的字节数组。

[[_creating_buffers]]
=== 创建 Buffer

可以使用静态方法 `link:../../apidocs/io/vertx/core/buffer/Buffer.html#buffer--[Buffer.buffer]` 来创建 Buffer。

Buffer可以从字符串或字节数组初始化，或者直接创建空的Buffer。

这儿有一些创建Buffer的例子。

创建一个空的Buffer：

[source,java]
----
Buffer buff = Buffer.buffer();
----

从字符串创建一个Buffer，这个Buffer中的字符会以 UTF-8 格式编码：

[source,java]
----
Buffer buff = Buffer.buffer("some string");
----

从字符串创建一个Buffer，这个字符串会以指定的编码方式编码，例如：

[source,java]
----
Buffer buff = Buffer.buffer("some string", "UTF-16");
----

include::override/buffer_from_bytes.adoc[]

创建一个指定初始大小的Buffer。若您知道您的 Buffer会写入一定量的数据，
您可以在创建Buffer时指定它的大小，使这个Buffer在初始化时就分配了更多的内存，
比数据写入时重新调整大小效率更高。

注意以这种方式创建的Buffer是 *空的*。它不会创建一个填满了0的Buffer。代码如下：（译者注：这里说的“空的”、“不会填满0”，指的是buffer内部的游标会从头开始，并不是在说内存布局。这种实现方式和使用直觉是一致的，只不过明确通过文档进行描述有点奇怪。）

[source,java]
----
Buffer buff = Buffer.buffer(10000);
----

[[_writing_to_a_buffer]]
=== 向Buffer写入数据

向Buffer写入数据的方式有两种：追加和随机访问。
任何一种情况下 Buffer都会自动进行扩容，
所以你不会在使用Buffer时遇到 `IndexOutOfBoundsException`。

[[_appending_to_a_buffer]]
==== 追加到Buffer

您可以使用 `appendXXX` 方法追加数据到Buffer。
Buffer类提供了追加各种不同类型数据的追加写入方法。

因为 `appendXXX` 方法的返回值就是 Buffer 自身，所以它可以链式地调用:

[source,java]
----
Buffer buff = Buffer.buffer();

buff.appendInt(123).appendString("hello\n");

socket.write(buff);
----

[[_random_access_buffer_writes]]
==== 随机访问写Buffer

您还可以指定一个索引值，通过 `setXXX` 方法写入数据到 `Buffer`。
`setXXX` 也为各种不同数据类型提供了对应的方法。所有的 set 方法都会将索引值作为第一个参数
—— 这表示Buffer中开始写入数据的位置。

Buffer始终根据需要进行自动扩容。

[source,java]
----
Buffer buff = Buffer.buffer();

buff.setInt(1000, 123);
buff.setString(0, "hello");
----

[[_reading_from_a_buffer]]
=== 从Buffer中读取

可使用 `getXXX` 方法从 Buffer 中读取数据，`getXXX` 为各种不同数据类型提供了对应的方法，
这些方法的第一个参数是Buffer中待获取的数据的索引位置。

[source,java]
----
Buffer buff = Buffer.buffer();
for (int i = 0; i < buff.length(); i += 4) {
  System.out.println("int value at " + i + " is " + buff.getInt(i));
}
----

[[_working_with_unsigned_numbers]]
=== 使用无符号数

可使用 `getUnsignedXXX`、
`appendUnsignedXXX` 和 `setUnsignedXXX` 方法将无符号数从Buffer中读取或追加/设置到Buffer里。
这对于实现一个致力于优化带宽占用的网络协议的编解码器是非常有用的。

下边例子中，值 200 被设置到了仅占用一个字节的特定位置：

[source,java]
----
Buffer buff = Buffer.buffer(128);
int pos = 15;
buff.setUnsignedByte(pos, (short) 200);
System.out.println(buff.getUnsignedByte(pos));
----

控制台中显示 "200"。

[[_buffer_length]]
=== Buffer长度

可使用 `link:../../apidocs/io/vertx/core/buffer/Buffer.html#length--[length]` 方法获取Buffer长度，
Buffer的长度值是Buffer中包含的字节的最大索引 + 1。

[[_copying_buffers]]
=== 拷贝Buffer

可使用 `link:../../apidocs/io/vertx/core/buffer/Buffer.html#copy--[copy]` 方法创建一个Buffer的副本。

[[_slicing_buffers]]
=== 裁剪Buffer

裁剪得到的Buffer是完全依赖于原始Buffer的一个新的Buffer，换句话说，它不会对Buffer中的数据做拷贝。
使用 `link:../../apidocs/io/vertx/core/buffer/Buffer.html#slice--[slice]` 方法裁剪一个Buffer。

[[_buffer_re_use]]
=== Buffer 重用

将Buffer写入到一个Socket或其他类似位置后，Buffer就不可被重用了。
