Vert.x Core 提供了一套用于解析传递给程序的命令行参数的API。这套API也可以用于打印
命令行相关参数、选项的详细帮助信息。即使这些功能远离
Vert.x Core主题，该API已在 `link:../../apidocs/io/vertx/core/Launcher.html[Launcher]` 类中使用，因此您可以在 _fat-jar_ 
和 `vertx` 命令行工具中使用它们。此外，它支持多语言（可用于任何已支持的语言），并
可在 Vert.x Shell 中使用。

Vert.x CLI 提供了一个编程模型用以描述命令行界面，这个编程模型也可以视为一种语法解析器，这个语法解析器支持
不同类型的语法：

* POSIX 风格的选项参数 （例如： `tar -zxvf foo.tar.gz`）
* GNU 的长字符串风格的选项参数 （例如： `du --human-readable --max-depth=1`）
* Java 风格的属性参数 （例如： `java -Djava.awt.headless=true -Djava.net.useSystemProxies=true Foo`）
* 附带选项值的简短风格的选项参数 （例如： `gcc -O2 foo.c`）
* 包含单个连接符的长字符串风格的选项参数 (例如： `ant -projecthelp`）

使用这个命令行API只需要三个步骤：

1. 定义命令行接口
2. 解析用户输入的命令行
3. 进行查询/问答交互操作

=== 定义阶段

每个命令行界面都必须定义所要使用的选项和参数集合。这些选项和参数也需命名。
命令行API使用 `link:../../apidocs/io/vertx/core/cli/Option.html[Option]` 和 `link:../../apidocs/io/vertx/core/cli/Argument.html[Argument]` 类来
描述选项和参数：

[source,java]
----
CLI cli = CLI.create("copy")
    .setSummary("A command line interface to copy files.")
    .addOption(new Option()
        .setLongName("directory")
        .setShortName("R")
        .setDescription("enables directory support")
        .setFlag(true))
    .addArgument(new Argument()
        .setIndex(0)
        .setDescription("The source")
        .setArgName("source"))
    .addArgument(new Argument()
        .setIndex(1)
        .setDescription("The destination")
        .setArgName("target"));
----

As you can see, you can create a new `link:../../apidocs/io/vertx/core/cli/CLI.html[CLI]` using
`link:../../apidocs/io/vertx/core/cli/CLI.html#create-java.lang.String-[CLI.create]`. The passed string is the name of the CLI. Once created you
can set the summary and description. The summary is intended to be short (one line), while the description can
contain more details. Each option and argument are also added on the `CLI` object using the
`link:../../apidocs/io/vertx/core/cli/CLI.html#addArgument-io.vertx.core.cli.Argument-[addArgument]` and
`link:../../apidocs/io/vertx/core/cli/CLI.html#addOption-io.vertx.core.cli.Option-[addOption]` methods.

==== Options

An `link:../../apidocs/io/vertx/core/cli/Option.html[Option]` is a command line parameter identified by a _key_ present in the user command
line. Options must have at least a long name or a short name. Long name are generally used using a `--` prefix,
while short names are used with a single `-`. Names are case-sensitive; however, case-insensitive name matching
will be used during the <<query_interrogation_stage, Query / Interrogation Stage>> if no exact match is found.
Options can get a description displayed in the usage (see below). Options can receive 0, 1 or several values. An
option receiving 0 values is a `flag`, and must be declared using
`link:../../apidocs/io/vertx/core/cli/Option.html#setFlag-boolean-[setFlag]`. By default, options receive a single value, however, you can
configure the option to receive several values using `link:../../apidocs/io/vertx/core/cli/Option.html#setMultiValued-boolean-[setMultiValued]`:

[source,java]
----
CLI cli = CLI.create("some-name")
    .setSummary("A command line interface illustrating the options valuation.")
    .addOption(new Option()
        .setLongName("flag").setShortName("f").setFlag(true).setDescription("a flag"))
    .addOption(new Option()
        .setLongName("single").setShortName("s").setDescription("a single-valued option"))
    .addOption(new Option()
        .setLongName("multiple").setShortName("m").setMultiValued(true)
        .setDescription("a multi-valued option"));
----

Options can be marked as mandatory. A mandatory option not set in the user command line throws an exception during
the parsing:

[source,java]
----
CLI cli = CLI.create("some-name")
    .addOption(new Option()
        .setLongName("mandatory")
        .setRequired(true)
        .setDescription("a mandatory option"));
----

Non-mandatory options can have a _default value_. This value would be used if the user does not set the option in
the command line:

[source,java]
----
CLI cli = CLI.create("some-name")
    .addOption(new Option()
        .setLongName("optional")
        .setDefaultValue("hello")
        .setDescription("an optional option with a default value"));
----

An option can be _hidden_ using the `link:../../apidocs/io/vertx/core/cli/Option.html#setHidden-boolean-[setHidden]` method. Hidden option are
not listed in the usage, but can still be used in the user command line (for power-users).

If the option value is contrained to a fixed set, you can set the different acceptable choices:

[source,java]
----
CLI cli = CLI.create("some-name")
    .addOption(new Option()
        .setLongName("color")
        .setDefaultValue("green")
        .addChoice("blue").addChoice("red").addChoice("green")
        .setDescription("a color"));
----

Options can also be instantiated from their JSON form.

==== Arguments

Unlike options, arguments do not have a _key_ and are identified by their _index_. For example, in
`java com.acme.Foo`, `com.acme.Foo` is an argument.

Arguments do not have a name, there are identified using a 0-based index. The first parameter has the
index `0`:

[source,java]
----
CLI cli = CLI.create("some-name")
    .addArgument(new Argument()
        .setIndex(0)
        .setDescription("the first argument")
        .setArgName("arg1"))
    .addArgument(new Argument()
        .setIndex(1)
        .setDescription("the second argument")
        .setArgName("arg2"));
----

If you don't set the argument indexes, it computes it automatically by using the declaration order.

[source,java]
----
CLI cli = CLI.create("some-name")
    // will have the index 0
    .addArgument(new Argument()
        .setDescription("the first argument")
        .setArgName("arg1"))
    // will have the index 1
    .addArgument(new Argument()
        .setDescription("the second argument")
        .setArgName("arg2"));
----

The `argName` is optional and used in the usage message.

As options, `link:../../apidocs/io/vertx/core/cli/Argument.html[Argument]` can:

* be hidden using `link:../../apidocs/io/vertx/core/cli/Argument.html#setHidden-boolean-[setHidden]`
* be mandatory using `link:../../apidocs/io/vertx/core/cli/Argument.html#setRequired-boolean-[setRequired]`
* have a default value using `link:../../apidocs/io/vertx/core/cli/Argument.html#setDefaultValue-java.lang.String-[setDefaultValue]`
* receive several values using `link:../../apidocs/io/vertx/core/cli/Argument.html#setMultiValued-boolean-[setMultiValued]` - only the last argument
can be multi-valued.

Arguments can also be instantiated from their JSON form.

==== Usage generation

Once your `link:../../apidocs/io/vertx/core/cli/CLI.html[CLI]` instance is configured, you can generate the _usage_ message:

[source,java]
----
CLI cli = CLI.create("copy")
    .setSummary("A command line interface to copy files.")
    .addOption(new Option()
        .setLongName("directory")
        .setShortName("R")
        .setDescription("enables directory support")
        .setFlag(true))
    .addArgument(new Argument()
        .setIndex(0)
        .setDescription("The source")
        .setArgName("source"))
    .addArgument(new Argument()
        .setIndex(0)
        .setDescription("The destination")
        .setArgName("target"));

StringBuilder builder = new StringBuilder();
cli.usage(builder);
----

It generates an usage message like this one:

[source]
----
Usage: copy [-R] source target

A command line interface to copy files.

 -R,--directory   enables directory support
----

If you need to tune the usage message, check the `link:../../apidocs/io/vertx/core/cli/UsageMessageFormatter.html[UsageMessageFormatter]` class.

=== Parsing Stage

Once your `link:../../apidocs/io/vertx/core/cli/CLI.html[CLI]` instance is configured, you can parse the user command line to evaluate
each option and argument:

[source,java]
----
CommandLine commandLine = cli.parse(userCommandLineArguments);
----

The `link:../../apidocs/io/vertx/core/cli/CLI.html#parse-java.util.List-[parse]` method returns a `link:../../apidocs/io/vertx/core/cli/CommandLine.html[CommandLine]`
object containing the values. By default, it validates the user command line and checks that each mandatory options
and arguments have been set as well as the number of values received by each option. You can disable the
validation by passing `false` as second parameter of `link:../../apidocs/io/vertx/core/cli/CLI.html#parse-java.util.List-boolean-[parse]`.
This is useful if you want to check an argument or option is present even if the parsed command line is invalid.

You can check whether or not the
`link:../../apidocs/io/vertx/core/cli/CommandLine.html[CommandLine]` is valid using `link:../../apidocs/io/vertx/core/cli/CommandLine.html#isValid--[isValid]`.

[[query_interrogation_stage]]
=== Query / Interrogation Stage

Once parsed, you can retrieve the values of the options and arguments from the
`link:../../apidocs/io/vertx/core/cli/CommandLine.html[CommandLine]` object returned by the `link:../../apidocs/io/vertx/core/cli/CLI.html#parse-java.util.List-[parse]`
method:

[source,java]
----
CommandLine commandLine = cli.parse(userCommandLineArguments);
String opt = commandLine.getOptionValue("my-option");
boolean flag = commandLine.isFlagEnabled("my-flag");
String arg0 = commandLine.getArgumentValue(0);
----

One of your options can be marked as "help". If a user command line enabled a "help" option, the validation
won't fail, but you have the opportunity to check if the user asks for help:

[source,java]
----
CLI cli = CLI.create("test")
    .addOption(
        new Option().setLongName("help").setShortName("h").setFlag(true).setHelp(true))
    .addOption(
        new Option().setLongName("mandatory").setRequired(true));

CommandLine line = cli.parse(Collections.singletonList("-h"));

// The parsing does not fail and let you do:
if (!line.isValid() && line.isAskingForHelp()) {
  StringBuilder builder = new StringBuilder();
  cli.usage(builder);
  stream.print(builder.toString());
}
----

include::cli-for-java.adoc[]
