Event Bus 是可配置的，这对于以集群模式运行的 Event Bus 来说非常有用。
Event Bus 使用 TCP 连接发送和接收消息，因此可以通过 `link:../../apidocs/io/vertx/core/eventbus/EventBusOptions.html[EventBusOptions]` 对TCP连接进行全面的配置。
由于 Event Bus 既可以用作客户端又可以用作服务端，因此这些配置近似于 `link:../../apidocs/io/vertx/core/net/NetClientOptions.html[NetClientOptions]` 和 `link:../../apidocs/io/vertx/core/net/NetServerOptions.html[NetServerOptions]`。

[source,java]
----
VertxOptions options = new VertxOptions()
    .setEventBusOptions(new EventBusOptions()
        .setSsl(true)
        .setKeyStoreOptions(new JksOptions().setPath("keystore.jks").setPassword("wibble"))
        .setTrustStoreOptions(new JksOptions().setPath("keystore.jks").setPassword("wibble"))
        .setClientAuth(ClientAuth.REQUIRED)
    );

Vertx.clusteredVertx(options, res -> {
  if (res.succeeded()) {
    Vertx vertx = res.result();
    EventBus eventBus = vertx.eventBus();
    System.out.println("We now have a clustered event bus: " + eventBus);
  } else {
    System.out.println("Failed: " + res.cause());
  }
});
----

上边代码段描述了如何在Event Bus中使用SSL连接替换明文的TCP连接。

**警告** ：若要在集群模式下保证安全性，您 **必须** 将集群管理器配置成加密的或者加强安全规则。
参考集群管理器的文档获取更多细节。

Event Bus 的配置需要在集群的所有节点中保持一致。

`link:../../apidocs/io/vertx/core/eventbus/EventBusOptions.html[EventBusOptions]` 还允许您指定 Event Bus 是否运行在集群模式下，以及它的端口和主机信息（译者注：host，这里指网络socket绑定的地址）。

在容器中使用时，您还可以配置公共主机和端口号：（译者注：setClusterPublicHost 和 setClusterPublicPort 的功能在原文档上描述得不清晰，但是API文档上有详细描述。 在某些容器、云环境等场景下，本节点监听的地址，和其他节点连接本节点时使用的地址，是不同的。这种情况下则可以利用上面两个配置区分监听地址和公开暴露的地址。  ）

[source,java]
----
VertxOptions options = new VertxOptions()
    .setEventBusOptions(new EventBusOptions()
        .setClusterPublicHost("whatever")
        .setClusterPublicPort(1234)
    );

Vertx.clusteredVertx(options, res -> {
  if (res.succeeded()) {
    Vertx vertx = res.result();
    EventBus eventBus = vertx.eventBus();
    System.out.println("We now have a clustered event bus: " + eventBus);
  } else {
    System.out.println("Failed: " + res.cause());
  }
});
----